### ISSUE TITLE
REF : Add support to convert to and use inline Base64 images

### ISSUE THREAD

**Issue by MagicFab** [antonreshetov/mysigmail#49]
The HTML generated currently uses hosting at Amazon AWS as-is.

It would be useful to have the ability to choose the "inline" method to embed the images.

This nees conversion to Base64 and using a data: URI to embed the image.
See:

- https://tools.ietf.org/html/rfc2397
- https://en.wikipedia.org/wiki/Data_URI_scheme
- https://www.campaignmonitor.com/blog/email-marketing/2013/02/embedded-images-in-html-email/

**Comment by antonreshetov** [comment]
It's already passed... At first time, it was possible to convert a user-uploaded image to BASE64, but after this functionality was replaced with a regular upload on S3, because BASE64 was not correct or didn't render at all in some email clients

Also see - https://blog.mailtrap.io/2018/11/02/embedding-images-in-html-email-have-the-rules-changed/
