### ISSUE TITLE
change img source for social logo img in mysigmail

### ISSUE THREAD

**Issue by IonutDraniceanu12** [antonreshetov/mysigmail#54]
Hello,

I have seen that the social logo img are put on a aws server were they are uploaded, is there a way to put custom link for those images to upload in another place not being changed on a future update?

Thank you

**Comment by antonreshetov** [comment]
Hi @IonutDraniceanu12
I want to note that the MySigMaiL is not a paid service. Perhaps in the future another place will be chosen to store the images. I think it is possible that even in paid services like these, the location for storing images may ever change. And since the user copies the source code of the signature to insert it into the mail client, the links may be broken.

The functionality to insert arbitrary links for icons is not provided in the future.
