### ISSUE TITLE
Avatar/Banner broken images

### ISSUE THREAD

**Issue by JessIKan** [antonreshetov/mysigmail#58]
Hi!

I've been using mysigmail for a month or so, and I love it! Thanks a lot!! Such a great job ^_^

Recently I've noticed that my images (banner and avatar) are broken, and not displaying. Is there any incidence reported on this so I can fix it? I've changed the link to dropbox, and still not working...Images are less than 3MB. I would really appreciate if you could help me fix this problem. 

Thanks a lot in advance, and have a great day! :)
Jess

**Comment by antonreshetov** [comment]
Hi @JessIKan 
I'm sorry, but that's not the problem with this repository. The demo site you are using to create an email signature is my personal site. The hosting invoices, as well as the upload of images to AWS S3 are paid by me. The number of images uploaded is increasing and I am unfortunately not ready to pay for them. People don't make donations, so they're not interested in the app.

Since this is an open source you can install this application yourself locally or on your hosting site. You have the right to do what you want with it, because the repository is under the MIT license.

**Comment by JessIKan** [comment]
Oh...I see....Thanks a lot for your fast and kind response!
Have a beautiful day ahead :)



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
27/08/19,
01:36:29 pm
